# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchText', models.CharField(max_length=100)),
                ('urlText', models.CharField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('userlist', models.ManyToManyField(related_name='userlist', to='login.User')),
            ],
        ),
    ]
